countries = [
    "Albania",
    "Australia",
    "Bahrain",
    "Bangladesh",
    "Bolivia",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Cyprus",
    "Denmark",
    "Dominican Republic",
    "Ecuador",
    "Egypt, Arab Rep.",
    "El Salvador",
    "Eswatini",
    "Finland",
    "France",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Israel",
    "Italy",
    "Jamaica",
    "Jordan",
    "Kenya",
    "Korea, Rep.",
    "Kuwait",
    "Madagascar",
    "Malaysia",
    "Mali",
    "Malta",
    "Mauritius",
    "Mexico",
    "Morocco",
    "Netherlands",
    "Niger",
    "Nigeria",
    "Norway",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Portugal",
    "Romania",
    "Saudi Arabia",
    "Senegal",
    "Singapore",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tunisia",
    "Turkey",
    "United Kingdom",
    "United States",
]

indices = {
    "GDP (current US$)": "gdp",
    "Unemployment, total (% of total labor force) (modeled ILO estimate)": "unemployment",
    "Inflation, consumer prices (annual %)": "inflation",
    "Net trade in goods (BoP, current US$)": "net-trade-in-goods",
    "Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)": "labor-force-participation",
    "Foreign direct investment, net (BoP, current US$)": "foreign-direct-investment",
    "Gross domestic savings (current US$)": "gross-domestic-product",
}
